---
- name: Custom Firewall Deploy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Configure Custom Firewall
      ansible_custom:
        name: Ansible_Custom
        protocol: tcp
        rules:
          - allow: 80
          - allow: 443
          - allow: 22
      register: firewall_result

    - name: Display Firewall Configuration Result
      debug:
        var: firewall_result
